# Generated by Django 3.1.1 on 2020-09-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarromGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Number', models.IntegerField()),
                ('Player1_Name', models.TextField()),
                ('Player2_Name', models.TextField()),
                ('winners_Name', models.TextField()),
            ],
        ),
    ]
