# Generated by Django 3.1.1 on 2020-09-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarromGame',
            new_name='Game',
        ),
    ]
