# Generated by Django 3.1.1 on 2020-09-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20200928_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarromGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Number', models.IntegerField()),
                ('winners_Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Number', models.IntegerField()),
                ('winners_Name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
